import{a as E,S as R,i as c}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&d(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const $="51453330-23ef603bbdd92dbcc1cebb640",x="https://pixabay.com/api/";async function h(r,o=1){const e={key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await E.get(x,{params:e})).data}const g=document.querySelector(".gallery"),b=document.querySelector(".loader"),L=document.querySelector(".load-more"),M=new R(".gallery a",{captionsData:"title",captionDelay:250,captionSelector:"self"});function v(r){const o=r.map(e=>`
  <li class="gallery-item">
    <a href="${e.largeImageURL}" title="${e.tags}">
      <img src="${e.webformatURL}" alt="${e.tags}" />
    </a>
    <div class="info">
      <p><b>Likes:</b> ${e.likes}</p>
      <p><b>Views:</b> ${e.views}</p>
      <p><b>Comments:</b> ${e.comments}</p>
      <p><b>Downloads:</b> ${e.downloads}</p>
    </div>
  </li>
`).join("");g.insertAdjacentHTML("beforeend",o),M.refresh()}function T(){g.innerHTML=""}function w(){b.classList.add("is-visible")}function S(){b.classList.remove("is-visible")}function q(){L.classList.add("is-visible")}function P(){L.classList.remove("is-visible")}const B=document.querySelector(".form"),A=B.querySelector('input[name="search-text"]'),I=document.querySelector(".load-more");let i=1,p="",m=0;B.addEventListener("submit",async r=>{r.preventDefault();const o=A.value.trim();if(!o){c.warning({message:"Please enter a search term",position:"topRight"});return}p=o,i=1,T(),P(),w();try{const e=await h(p,i);m=e.totalHits,e.hits.length===0?c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(v(e.hits),m>i*15&&q())}catch{c.error({message:"An error occurred. Please try again later.",position:"topRight"})}finally{S()}});I.addEventListener("click",async()=>{i+=1,w(),P();try{const r=await h(p,i);v(r.hits),H();const o=Math.ceil(m/15);i<o?q():c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{c.error({message:"An error occurred. Please try again later.",position:"topRight"})}finally{S()}});function H(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}const O=document.getElementById("typewriter"),y=["Search images...","Find your favorite...",'Try "nature" or "sky"'];let f=0,n=0,a=!1;function l(){const r=y[f],o=r.slice(0,n);O.setAttribute("placeholder",o),!a&&n<r.length?(n++,setTimeout(l,100)):a&&n>0?(n--,setTimeout(l,50)):(a=!a,a||(f=(f+1)%y.length),setTimeout(l,1e3))}l();const D=document.querySelector(".theme-toggle");D.addEventListener("click",()=>{document.body.classList.toggle("dark")});
//# sourceMappingURL=index.js.map
