import{a as w,S,i as n}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const q="51453330-23ef603bbdd92dbcc1cebb640",P="https://pixabay.com/api/";async function u(o,r=1){const e={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await w.get(P,{params:e})).data}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".load-more"),R=new S(".gallery a",{captionsData:"title",captionDelay:250,captionSelector:"self"});function y(o){const r=o.map(e=>`
  <li class="gallery-item">
    <a href="${e.largeImageURL}" title="${e.tags}">
      <img src="${e.webformatURL}" alt="${e.tags}" />
    </a>
    <div class="info">
      <p><b>Likes:</b> ${e.likes}</p>
      <p><b>Views:</b> ${e.views}</p>
      <p><b>Comments:</b> ${e.comments}</p>
      <p><b>Downloads:</b> ${e.downloads}</p>
    </div>
  </li>
`).join("");f.insertAdjacentHTML("beforeend",r),R.refresh()}function $(){f.innerHTML=""}function h(){p.classList.add("is-visible")}function g(){p.classList.remove("is-visible")}function b(){m.classList.add("is-visible")}function L(){m.classList.remove("is-visible")}const v=document.querySelector(".form"),B=v.querySelector('input[name="search-text"]'),M=document.querySelector(".load-more");let i=1,l="",d=0;v.addEventListener("submit",async o=>{o.preventDefault();const r=B.value.trim();if(!r){n.warning({message:"Please enter a search term",position:"topRight"});return}l=r,i=1,$(),L(),h();try{const e=await u(l,i);d=e.totalHits,e.hits.length===0?n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(y(e.hits),d>i*15&&b())}catch{n.error({message:"An error occurred. Please try again later.",position:"topRight"})}finally{g()}});M.addEventListener("click",async()=>{i+=1,h(),L();try{const o=await u(l,i);y(o.hits),E();const r=Math.ceil(d/15);i<r?b():n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{n.error({message:"An error occurred. Please try again later.",position:"topRight"})}finally{g()}});function E(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}const A=document.querySelector(".theme-toggle");A.addEventListener("click",()=>{document.body.classList.toggle("dark")});
//# sourceMappingURL=index.js.map
